#!/bin/bash
project="sheer_third_party"
project_length=${#project}
# Get pwd string
cd ..
path=$(pwd)
# Get last project_length chars
suffix="${path: -$project_length}"
if [ "$suffix" = "$project" ]; then
    echo "------------------ lua script start ------------------"
else
    echo "Path error.Please ensure that the last few strings after using pwd are "$project
    exit 1  # stop
fi

install_path=$(pwd)

LUA_DIR="$install_path/libraries/lua"
LUAROCKS_DIR="$install_path/libraries/luarocks"

export LUA_PATH="$LUA_DIR/share/lua/5.3/?.lua;$LUA_DIR/share/lua/5.3/?/init.lua;$LUAROCKS_DIR/share/lua/5.3/?.lua;$LUAROCKS_DIR/share/lua/5.3/?/init.lua;;"
export LUA_CPATH="$LUA_DIR/lib/lua/5.3/?.so;$LUAROCKS_DIR/lib/lua/5.3/?.so;;"

cd lua_test
# Run the Lua script with the provided arguments
$LUA_DIR/lua "$@"
