#!/bin/bash
project="sheer_third_party"
project_length=${#project}
# Get pwd string
cd ..
path=$(pwd)
# Get last project_length chars
suffix="${path: -$project_length}"
if [ "$suffix" = "$project" ]; then
    echo "------------------ luarocks script start ------------------"
else
    echo "Path error.Please ensure that the last few strings after using pwd are "$project
    exit 1  # stop
fi

install_path=$(pwd)

LUAROCKS_PATH="$install_path/libraries/luarocks/bin/luarocks"

cd lua_test
# Run the Lua script with the provided arguments
$LUAROCKS_PATH "$@"
